
baseURL = 'https://example.org/'
languageCode = 'it-it'
title = 'Marco Demontis Impianti Elettrici'

[module]
  replacements = "github.com/liuuuk311/hugo-minimal-smb -> ../../.."
  [[module.imports]]
    path = "github.com/liuuuk311/hugo-minimal-smb"
  
  [[module.imports]]
    path = "github.com/hugo-mods/icons"

[params]
  logo = "images/logo.png"
  defaultHero = "images/home/hero_full.png"
  
  [params.theme]
    primaryColor = "#171A1A"
    accentColor = "#d95f2b"
    backgroundColor = "#F3F5F4"
    surfaceColor = "#ffffff"
    textColor = "#222727"
    inverseTextColor = "#F3F5F4"
    heroType = "sideImage"
    heroGradientBlur = true
    heroGradientColor = 'light'
    borderRadius = "lg"

  [[params.social]]
    url = "https://whatsapp.com/username"
    icon = "fab whatsapp"

  [[params.social]]
    url = "https://twitter.com/username"
    icon = "fab twitter"

  [[params.social]]
    url = "https://facebook.com/username"
    icon = "fab facebook"

  [[params.social]]
    url = "https://instagram.com/username"
    icon = "fab instagram"

  [[params.social]]
    url = "https://tiktok.com/username"
    icon = "fab tiktok"

  [params.footer]
    headline = "Servizi elettrici con garanzia di qualità"
    addressTitle = "Indirizzo"
    address = "Italia —<br>Via Lazzaretto, 18, 22033 Asso CO"
    contactTitle = "Contattaci"
  
  [params.contacts]
    phoneNumber = "+39031670483"
    emailAddress = "azienda@marcodemontis.it"
    workingHours = "Non specificato"
    workingDays = "Nessun giorno lavorativo specificato"

  [params.header]
    CTAText = "+39 031 670483"
    CTAUrl = "tel:+39031670483"
    subHeading = "Orari non specificati"
    secondaryCTAText = "Prenota online"
    secondaryCTAUrl = "#"

  [params.reviews]
    image = "images/google.png"
    rating = 4.8
    reviewText = "(73 recensioni)"
    reviewUrl = "#"
