
baseURL = 'https://example.org/'
languageCode = 'it'
title = 'A & B Termoidraulica'

[module]
  replacements = "github.com/liuuuk311/hugo-minimal-smb -> ../../.."
  [[module.imports]]
    path = "github.com/liuuuk311/hugo-minimal-smb"
  
  [[module.imports]]
    path = "github.com/hugo-mods/icons"

[params]
  logo = "images/logo.webp"
  defaultHero = "images/home/hero_full.jpg"
  
  [params.theme]
    primaryColor = "#171A1A"      
    accentColor = "#10727B"       
    backgroundColor = "#F3F5F4"   
    surfaceColor = "#ffffff"      
    textColor = "#222727"         
    inverseTextColor = "#bcbcbc"  
    heroType = "sideImage"        
    heroGradientBlur = true       
    heroGradientColor = 'light'   
    borderRadius = "lg"

  [[params.social]]
    url = "https://facebook.com/username"
    icon = "fab facebook"

  [[params.social]]
    url = "https://twitter.com/username"
    icon = "fab twitter"

  [[params.social]]
    url = "https://youtube.com/username"
    icon = "fab youtube"

  [params.footer]
    headline = "Esperienza e professionalità al tuo servizio"
    addressTitle = "Indirizzo"
    address = "via degli artigiani, 10/A<br>Tremezzina (CO) loc. Mezzegra"
    contactTitle = "Contattaci"
  
  [params.contacts]
    phoneNumber = "0344 42173"
    emailAddress = "info@aeb-termoidraulica.it"
    workingHours = "Lun. - Ven. 08:00 - 17:00<br>Sab. 09:00 - 12:00"
    workingDays = "Lunedì a Sabato"

  [params.header]
    CTAText = "0344 42173"
    CTAUrl = "tel:034442173"
    subHeading = "Lun. a Ven. - 08:00 a 17:00, Sab. - 09:00 a 12:00"
    secondaryCTAText = "Scrivici"
    secondaryCTAUrl = "mailto:info@aeb-termoidraulica.it"

  [params.reviews]
    image = "images/google.png"
    rating = 4.8
    reviewText = "(73 recensioni)"
    reviewUrl = "#"
